### ISSUE TITLE
Create vagrantfile

### ISSUE THREAD

**Issue by IJaykkk** [devops-customers-18/customers#1]
**As a** developer
**I need** a vagrantfile
**So that** I can start coding

**Assumptions:** 

* We will use PostgreSQL as the persistent store
* A PosgreSQL service from Bluemix should be used

**Acceptance Criteria:**

```
We can develop the app on different machines

type docker ps will show two images

1. flask 
2. postgre

```

**Comment by IJaykkk** [comment]
@o9812 Thanks.

**Comment by IJaykkk** [comment]
It seems to me we still need to specify a test db in the vagrant

**Comment by weikaipan** [comment]
I think this branch could be merged into the master first. Then creating a new issue specifying more details in the vagrant file.
