### ISSUE TITLE
Add Query function into RESTful API

### ISSUE THREAD

**Issue by slydomon** [devops-customers-18/customers#10]
**As a** user
**I need**  query function
**So that** I can query customer data by some attribute of the customers.

**Assumptions:** 

* A call to ```GET http.../customers?attribute="condition"``` should retrieve all customer data that match the required attribute.

* A call to ```GET http.../customers?attribute-1="condition-1"&attribute-2="condition-2"``` should retrieve all customer data that match both attribute-1 and attribute-2.

* A call to ```GET http.../customers?attribute-1="condition-1"|attribute-2="condition-2"``` should retrieve all customer data that match both attribute-1 or attribute-2.

**Acceptance Criteria:**

*When I call  ```GET http.../customers?attribute="condition"```,  I should obtain all customer data that match the required attribute.

*When I call  ```GET http.../customers?attribute-1="condition-1"&attribute-2="condition-2"```,  I should obtain all customer data that match both attribute-1 and attribute-2.

*When I call  ```GET http.../customers?attribute-1="condition-1"|attribute-2="condition-2"```,  I should obtain all customer data that match either attribute-1 or attribute-2.

*When I call ```GET http...``` and there is no customer data that match the required attribute, return 204(No content).

**Comment by o9812** [comment]
"|" is not valid for flask parse the http
