### ISSUE TITLE
Add the ability to create new customer accounts

### ISSUE THREAD

**Issue by weikaipan** [devops-customers-18/customers#5]
**As a** User
**I need** the ability to create a customer account in the database
**So that** the service can track my identity

**Assumptions:** 
* A call to POST `/customers` should save the first name and last name of the customer

**Acceptance Criteria:**
```
When I call POST /customers
The service inserts a new entry/ document inside the database
When the call POST /customers succeeds
The service notifies the success by returning a json string
When the call POST /customers fails
The service shows an error page by returning a json string
```

**Comment by o9812** [comment]
the attribute id should be integer
