### ISSUE TITLE
Perform some Action on the Resource

### ISSUE THREAD

**Issue by o9812** [devops-customers-18/customers#6]
**As a** User

**I need** to perform action as I expect

**So that** the action can be executed to the resource.

**Assumptions:** 

Each action should be executed correctly.

**Acceptance Criteria:**

```

When I perform the action on resource

either I will get the result as what the action should return

or I get error message from the action if it fails to execute.

```

**Comment by o9812** [comment]
We feel a little bit confused, so we will discuss this in class for more detail.

**Comment by o9812** [comment]
example of action:
disable a client (a convenient way)
change the state of resource

**Comment by weikaipan** [comment]
Add an active field in the user table
