### ISSUE TITLE
Add a "Delete" function into RESTful API.

### ISSUE THREAD

**Issue by slydomon** [devops-customers-18/customers#8]
**As a** user
**I need**  delete function
**So that** I can delete customer data by some attribute of the customers.

**Assumptions:** 

* A call to ```DELETE http.../customers?attribute="condition"``` should delete all customer data that match the required attribute.

* A call to ```DELETE http.../customers?attribute-1="condition-1"&attribute-2="condition-2"``` should delete all customer data that match both attribute-1 and attribute-2.

* A call to ```DELETE http.../customers?attribute-1="condition-1"|attribute-2="condition-2"``` should delete all customer data that match both attribute-1 and attribute-2.

**Acceptance Criteria:**
* When I call  ```DELETE http.../customers?attribute="condition"```,  I should delete all customer data that match the required attribute.

* When I call  ```DELETE http.../customers?attribute-1="condition-1"&attribute-2="condition-2"```,  I should delete all customer data that match both attribute-1 and attribute-2.

* When I call  ```DELETE http.../customers?attribute-1="condition-1"|attribute-2="condition-2"```,  I should delete all customer data that match either attribute-1 or attribute-2.

* When I call ```DELETE http...``` and the system fail to delete(data are still there), return 302 and redirect to a page that specifies the reason of failure.

**Comment by weikaipan** [comment]
Not sure if attributes should be included in the REST representation.

**Comment by slydomon** [comment]
Hi guy, I did some homework indicating that if we want to handle complex query such as (id=1|id=3)&(birthday=10/2/1988), it will require some extra effort. Thus, for now, I think I just handle the "and" case, and then let's discuss about that at meeting on 10/12
