### ISSUE TITLE
Refactor the models.py and customer_collection.py

### ISSUE THREAD

**Issue by weikaipan** [devops-customers-18/customers#80]
**As a** developer 
**I need** to user Couch DB as my persistence
**So that** the application can use Cloudant on ibm bluemix

**Assumptions:** 

* using couch db locally and Cloudant on ibm bluemix

**Acceptance Criteria:**

```
Pass all model tests and 95% coverage.

```

**Comment by o9812** [comment]
This belongs Part2

**Comment by weikaipan** [comment]
The server tests should also be improved here as well

**Comment by weikaipan** [comment]
All server tests coverage are 100%, now keep working on model coverage.

The main functions to test are CLOUDANT_BINDING test

**Comment by o9812** [comment]
I don't get it. The test for homepage broke.

**Comment by weikaipan** [comment]
This branch: 80-refactor-model. The test for homepage passed.
I haven't issued the PR
