### ISSUE TITLE
Show a customer

### ISSUE THREAD

**Issue by IJaykkk** [devops-customers-18/customers#9]
**As an** user
**I need** an ability to show a specific customer
**So that** someone can see related attributes of a customer

**Assumptions:** 
A call to GET `/customers/123` will show the customer with id 123

**Acceptance Criteria:**
When I call GET `/customers/:id`
I should get the related data for the customer `id` as a JSON string
```

**Comment by o9812** [comment]
Not sure the assumption is correct or not. (the difference among assumption and acceptance Criteria)
